# Parameters

In [1]:
import os

import numpy as np
# set n and k
n = int(1e3)
k = int(1e1)

# set folder name based on n
n_readable = f"{n:.0e}".replace(".0", "").replace("+0", "")
experiment_dim = "dim_" + n_readable
save_folder = "./private/data/"+experiment_dim+"/"

# create folder if it doesn't exist
os.makedirs(save_folder, exist_ok=True)


# check if n/k has no remainder
if n % k == 0:
    # if it has no remainder, we can simply divide n by k
    m = n // k
    sizes = [n // k] * k
else: 
    exit("n must be divisible by k")
    raise ValueError("n must be divisible by k")


print(f"n: {n}, k: {k}, sizes: {sizes}")

n: 1000, k: 10, sizes: [100, 100, 100, 100, 100, 100, 100, 100, 100, 100]


# Generate U

In [2]:
from scipy.stats import ortho_group
U = ortho_group.rvs(n)

# print the matrix
np.set_printoptions(precision=3, suppress=True, linewidth=200)
print(U)

[[-0.003  0.013 -0.006 ...  0.037 -0.036 -0.05 ]
 [-0.015 -0.002 -0.02  ... -0.009  0.015  0.018]
 [-0.021  0.009 -0.014 ...  0.033 -0.028 -0.009]
 ...
 [-0.036 -0.022 -0.053 ...  0.013 -0.026  0.001]
 [-0.041  0.039  0.015 ...  0.045  0.02   0.021]
 [ 0.008  0.079  0.083 ...  0.025  0.046  0.02 ]]


# well defined case

## Diag well

In [3]:
import numpy as np

# create a diagonal matrix with n random values on the diagonal greater or equal to 0 in the interval [0,10]
D_well = np.diag(np.random.rand(n) * 10)

# get one random index to set to 0
random_index = np.random.randint(0, n)
D_well[random_index, random_index] = 0

# count how many indexes are 0
num_zeros = np.sum(np.diag(D_well) == 0)
print(f"Number of zeros in the diagonal: {num_zeros}")

#print the matrix
np.set_printoptions(precision=3, suppress=True, linewidth=200)
print(D_well)

Number of zeros in the diagonal: 1
[[7.628 0.    0.    ... 0.    0.    0.   ]
 [0.    0.225 0.    ... 0.    0.    0.   ]
 [0.    0.    1.066 ... 0.    0.    0.   ]
 ...
 [0.    0.    0.    ... 1.225 0.    0.   ]
 [0.    0.    0.    ... 0.    9.81  0.   ]
 [0.    0.    0.    ... 0.    0.    1.616]]


## Q_well

In [4]:
Q_well = U @ D_well @ U.T

# Ill defined case

## Diag ill

In [5]:
import numpy as np

# create a diagonal matrix with n random values on the diagonal greater or equal to 0 in the interval [0,10e4]
D_ill = np.diag(np.random.rand(n) * 10e4)

# get one random index to set to 0
random_index = np.random.randint(0, n)
D_ill[random_index, random_index] = 0

# count how many indexes are 0
num_zeros = np.sum(np.diag(D_ill) == 0)
print(f"Number of zeros in the diagonal: {num_zeros}")

#print the matrix
np.set_printoptions(precision=3, suppress=True, linewidth=200)
print(D_ill)

Number of zeros in the diagonal: 1
[[84643.399     0.        0.    ...     0.        0.        0.   ]
 [    0.    59086.349     0.    ...     0.        0.        0.   ]
 [    0.        0.    24302.19  ...     0.        0.        0.   ]
 ...
 [    0.        0.        0.    ... 18618.413     0.        0.   ]
 [    0.        0.        0.    ...     0.    37197.009     0.   ]
 [    0.        0.        0.    ...     0.        0.     9583.897]]


## Q_ill

In [6]:
Q_ill = U @ D_ill @ U.T

# Save everything

In [7]:
# save the matrices U,D_ill, D_well,Q_ill,Q_well in npz file compressed
np.savez_compressed(save_folder + "matrices.npz", U=U, D_ill=D_ill, D_well=D_well, Q_ill=Q_ill, Q_well=Q_well)